ecommerce_dbt:
  target: dev
  outputs:
    dev:
      type: bigquery
      location: US
      method: service-account
      project: "{{ env_var('GCP_PROJECT_ID') }}"
      dataset: ga4_staging
      job_execution_timeout_seconds: 300
      job_retries: 1
      keyfile: "{{ env_var('GCP_KEYFILE_JSON') }}"
 
