name: dbt CI

on:
  push:
    branches: 
      - main   # parte quando fai push su main
  pull_request:
    branches:
      - main   # parte anche su PR verso main
jobs:
  dbt:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: gcp-key.json
      GCP_PROJECT_ID: ${{ secrets.GCP_PROJECT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dbt AND dependencies
        run: |
          pip install dbt-bigquery

      - name: Write GCP key file from Base64
        run: |
          echo "${{ secrets.GCP_KEY_BASE64 }}" | base64 --decode > gcp-key.json

      - name: Authenticate with GCP
        run: |
          gcloud auth activate-service-account --key-file=gcp-key.json
          gcloud config set project "${{ secrets.GCP_PROJECT_ID }}"

      - name: Run dbt build
        run: |
          cd ecommerce_dbt
          dbt deps
          dbt build --profiles-dir .